apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-repo
  namespace: flux-system
spec:
  interval: 1m0s # detect drift and undo kubectl edits every hour
  wait: true # wait for all applied resources to become ready
  prune: true # remove stale resources from cluster
  force: true # recreate resources on immutable fields changes
  sourceRef:
    kind: GitRepository
    name: flux-repo
